name: Feature Request
description: Suggest a new feature or enhancement for Forge
title: "[Feature]: "
labels: ["enhancement", "needs-triage"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for suggesting a new feature! Please provide as much detail as possible to help us understand your request.

  - type: textarea
    id: problem
    attributes:
      label: Problem Statement
      description: Is your feature request related to a problem? Please describe.
      placeholder: I'm frustrated when...
    validations:
      required: true

  - type: textarea
    id: solution
    attributes:
      label: Proposed Solution
      description: Describe the solution you'd like to see
      placeholder: I would like to see...
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives Considered
      description: Describe any alternative solutions or features you've considered
      placeholder: I've considered...

  - type: dropdown
    id: component-type
    attributes:
      label: Feature Type
      description: What type of feature is this?
      options:
        - New Component
        - Component Enhancement
        - Framework Integration
        - Developer Tools
        - Documentation
        - Performance
        - Accessibility
        - Design System
        - AI Integration
        - Other
    validations:
      required: true

  - type: dropdown
    id: priority
    attributes:
      label: Priority
      description: How important is this feature to you?
      options:
        - Low - Nice to have
        - Medium - Would improve my workflow
        - High - Blocking my use case
    validations:
      required: true

  - type: textarea
    id: use-case
    attributes:
      label: Use Case
      description: Describe your use case for this feature
      placeholder: |
        I'm building... and I need this feature to...
    validations:
      required: true

  - type: textarea
    id: example
    attributes:
      label: Example API/Usage
      description: Show how you envision using this feature
      render: typescript
      placeholder: |
        // Example of how the feature would be used
        import { NewFeature } from '@nexcraft/forge';

        const example = new NewFeature({
          // configuration
        });

  - type: textarea
    id: reference
    attributes:
      label: Reference Examples
      description: Are there examples of this feature in other libraries?
      placeholder: |
        - Library X does this: [link]
        - Framework Y has similar functionality: [link]

  - type: dropdown
    id: breaking
    attributes:
      label: Breaking Change
      description: Would this require breaking changes to existing APIs?
      options:
        - "No - Backward compatible"
        - "Yes - Would break existing code"
        - "Unknown"
    validations:
      required: true

  - type: textarea
    id: additional
    attributes:
      label: Additional Context
      description: Any other context, mockups, or information about the feature request
      placeholder: Add any other context, mockups, or screenshots

  - type: checkboxes
    id: terms
    attributes:
      label: Checklist
      description: Please confirm the following
      options:
        - label: I have searched for existing feature requests
          required: true
        - label: This feature aligns with Forge's goal as a web component library
          required: true
        - label: I would be willing to contribute this feature
          required: false
