import type { Config } from "tailwindcss";

export default {
  content: [
    "./src/pages/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/components/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/app/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  theme: {
    extend: {
      colors: {
        background: "var(--background)",
        foreground: "var(--foreground)",
        // Forge UI color integration
        primary: {
          50: 'var(--forge-color-primary-50)',
          100: 'var(--forge-color-primary-100)',
          200: 'var(--forge-color-primary-200)',
          300: 'var(--forge-color-primary-300)',
          400: 'var(--forge-color-primary-400)',
          500: 'var(--forge-color-primary-500)',
          600: 'var(--forge-color-primary-600)',
          700: 'var(--forge-color-primary-700)',
          800: 'var(--forge-color-primary-800)',
          900: 'var(--forge-color-primary-900)',
        },
        neutral: {
          50: 'var(--forge-color-neutral-50)',
          100: 'var(--forge-color-neutral-100)',
          200: 'var(--forge-color-neutral-200)',
          300: 'var(--forge-color-neutral-300)',
          400: 'var(--forge-color-neutral-400)',
          500: 'var(--forge-color-neutral-500)',
          600: 'var(--forge-color-neutral-600)',
          700: 'var(--forge-color-neutral-700)',
          800: 'var(--forge-color-neutral-800)',
          900: 'var(--forge-color-neutral-900)',
        },
        success: 'var(--forge-color-success-500)',
        warning: 'var(--forge-color-warning-500)',
        danger: 'var(--forge-color-danger-500)',
        info: 'var(--forge-color-info-500)',
      },
      fontFamily: {
        sans: 'var(--forge-font-family)',
        mono: 'var(--forge-font-family-mono)',
      },
      fontSize: {
        xs: 'var(--forge-font-size-xs)',
        sm: 'var(--forge-font-size-sm)',
        base: 'var(--forge-font-size-base)',
        lg: 'var(--forge-font-size-lg)',
        xl: 'var(--forge-font-size-xl)',
        '2xl': 'var(--forge-font-size-2xl)',
        '3xl': 'var(--forge-font-size-3xl)',
        '4xl': 'var(--forge-font-size-4xl)',
      },
      spacing: {
        xs: 'var(--forge-spacing-xs)',
        sm: 'var(--forge-spacing-sm)',
        md: 'var(--forge-spacing-md)',
        lg: 'var(--forge-spacing-lg)',
        xl: 'var(--forge-spacing-xl)',
        '2xl': 'var(--forge-spacing-2xl)',
        '3xl': 'var(--forge-spacing-3xl)',
      },
      borderRadius: {
        sm: 'var(--forge-border-radius-sm)',
        DEFAULT: 'var(--forge-border-radius-md)',
        md: 'var(--forge-border-radius-md)',
        lg: 'var(--forge-border-radius-lg)',
        xl: 'var(--forge-border-radius-xl)',
        full: 'var(--forge-border-radius-full)',
      },
      boxShadow: {
        xs: 'var(--forge-shadow-xs)',
        sm: 'var(--forge-shadow-sm)',
        DEFAULT: 'var(--forge-shadow-md)',
        md: 'var(--forge-shadow-md)',
        lg: 'var(--forge-shadow-lg)',
        xl: 'var(--forge-shadow-xl)',
        '2xl': 'var(--forge-shadow-2xl)',
      },
      transitionDuration: {
        fast: 'var(--forge-transition-fast)',
        DEFAULT: 'var(--forge-transition-base)',
        slow: 'var(--forge-transition-slow)',
        slower: 'var(--forge-transition-slower)',
      },
    },
  },
  plugins: [],
} satisfies Config;